/******************************************************************************/
/***          Generated by IBExpert 2011.01.11 17.01.2011 21:49:41          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'localhost:F:\_Projects_\fbgwkino\db\fbgwkino.fdb'
USER 'DEVEL001' PASSWORD 'primarykey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;

